name: ai_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.3"

dependencies:
  chat_gpt_sdk: ^3.0.4
  flutter:
    sdk: flutter
  generative_ai_dart: ^0.1.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
