name: task_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.3"

dependencies:
  cloud_firestore: ^4.9.3
  collection: ^1.17.2
  flutter:
    sdk: flutter
  integrations_repository:
    path: ../integrations_repository
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
